# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('conference_name', models.CharField(max_length=75)),
                ('conference_info', models.TextField()),
                ('conference_address', models.CharField(max_length=50)),
                ('conference_city', models.CharField(max_length=20)),
                ('conference_state', models.CharField(max_length=20)),
                ('attendee_count', models.IntegerField()),
                ('available_count', models.IntegerField()),
                ('header_path', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=256)),
                ('approval_flag', models.BooleanField(default=False)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Conference')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserConference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[(b'A', b'Admin'), (b'R', b'Reviewer'), (b'G', b'Guest'), (b'S', b'Submitter')], max_length=1)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Conference')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Items'),
        ),
    ]
