# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-04 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
