# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20170320_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='conference_dateTime',
            field=models.DateTimeField(default='1970-01-01T01:00:00Z'),
            preserve_default=False,
        ),
    ]
